#!/usr/bin/env python3
"""Extract the reading rows the Inner Compass shows from Model 2's canon tables.

Reads 03-model-2-gradient/positions.html (the carried Gradient page), walks
the Fluid and Chronic panels, and writes every seven-cell row as text into
06-inner-compass-four-modes/data/readings.js. The Compass view reads that
file, so its cards are always Model 2's own words. Re-run after carry.py.
"""

from __future__ import annotations

import json
import re
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "03-model-2-gradient" / "positions.html"
TARGET = ROOT / "06-inner-compass-four-modes" / "data" / "readings.js"
POSITIONS = ["X", "A", "A↔B", "B", "C", "D", "Z"]
SKIP_SPANS = {"row-alias", "row-pair", "cell-hooks", "swatch"}


class TableWalker(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.panel: str | None = None
        self.depth = 0
        self.rows: dict[str, list[tuple[str, list[str]]]] = {"fluid": [], "chronic": []}
        self.in_row = False
        self.cell: list[str] | None = None
        self.cell_kind: str | None = None
        self.header = ""
        self.cells: list[str] = []
        self.skip = 0

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag == "section" and a.get("id") in ("panel-fluid", "panel-chronic"):
            self.panel = a["id"].split("-")[1]
            self.depth = 0
        if self.panel:
            if tag == "section":
                self.depth += 1
            if tag == "tr":
                self.in_row, self.header, self.cells = True, "", []
            elif self.in_row and tag in ("th", "td"):
                self.cell, self.cell_kind = [], tag
                if tag == "td" and a.get("colspan"):
                    self.cell_kind = "skip"
            elif self.cell is not None and tag in ("span", "i", "small") and (set((a.get("class") or "").split()) & SKIP_SPANS):
                self.skip += 1
            elif self.cell is not None and self.skip:
                self.skip += 1

    def handle_endtag(self, tag):
        if not self.panel:
            return
        if self.cell is not None and self.skip and tag in ("span", "i", "small", "a", "strong", "em", "b"):
            self.skip -= 1
            return
        if tag in ("th", "td") and self.cell is not None:
            text = re.sub(r"\s+", " ", "".join(self.cell)).strip()
            text = re.sub(r"#[0-9a-fA-F]{6}$", "", text).strip()
            if self.cell_kind == "th":
                self.header = text
            elif self.cell_kind == "td":
                self.cells.append(text)
            self.cell, self.cell_kind = None, None
        elif tag == "tr" and self.in_row:
            if self.header and len(self.cells) == 7:
                self.rows[self.panel].append((self.header, self.cells))
            self.in_row = False
        elif tag == "section":
            self.depth -= 1
            if self.depth < 0:
                self.panel = None

    def handle_data(self, data):
        if self.cell is not None and not self.skip:
            self.cell.append(data)


def main() -> int:
    walker = TableWalker()
    walker.feed(SOURCE.read_text(encoding="utf-8"))
    out = {"positions": POSITIONS, "fluid": {}, "chronic": {}, "source": "03-model-2-gradient/positions.html"}
    for plane in ("fluid", "chronic"):
        for header, cells in walker.rows[plane]:
            key = header.split("ME slider")[0].strip()
            if key not in out[plane]:
                out[plane][key] = cells
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(
        "/* Generated by scripts/build-compass-data.py from Model 2's canon tables. Do not edit. */\n"
        "window.TEG_READINGS = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n",
        encoding="utf-8",
    )
    for plane in ("fluid", "chronic"):
        print(f"{plane}: {len(out[plane])} rows")
        for key in out[plane]:
            print("   ", key)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
