"""Site-owned presentation adapter. Does not alter Engine content or ownership."""
from pathlib import Path
import re, colorsys, os, json
ROOT = Path(__file__).resolve().parents[1]

def active(path, text):
    return path.endswith('.html') and not any(x in Path(path).parts for x in ('archive','notes')) and not (path == '02-model-1-ess-cls-me/access.html' or re.search(r'http-equiv=[\"\']refresh', text, re.I))

def adapt(css):
    # Preserve saturated conceptual colours; translate neutral surfaces and dark text.
    def declaration(m):
        prop, value = m.group(1), m.group(2)
        original_prop = prop
        if prop.startswith('--'):
            if (any(word in prop for word in ('wash','tint','-soft')) and prop not in ('--soft','--ink-soft')) or prop in ('--white','--fog'):
                prop = 'background'
            elif prop.startswith('--signal-') and 'line' not in prop:
                prop = 'color'
            else:
                return m.group(0)
        if prop in ('background','background-color'):
            value=value.replace('var(--ink)', 'var(--surface-3)').replace('var(--ink-2)', 'var(--surface-3)').replace('var(--head)', 'var(--surface-3)')
        def colour(c):
            raw=c.group(0)
            if raw.lower()=='white': rgb=(1,1,1)
            else:
                h=raw[1:]; h=''.join(x*2 for x in h) if len(h)==3 else h
                rgb=tuple(int(h[i:i+2],16)/255 for i in (0,2,4))
            hue,light,sat=colorsys.rgb_to_hls(*rgb)
            if prop in ('background','background-color') and light>.78:
                return 'var(--surface)' if sat<.12 else 'var(--surface-2)'
            if prop=='color' and light<.63:
                r,g,b=colorsys.hls_to_rgb(hue,max(.76,light),min(sat,.7))
                return '#%02x%02x%02x'%(round(r*255),round(g*255),round(b*255))
            if ('border' in prop or prop=='outline') and light>.78: return 'var(--line-strong)'
            return raw
        value=re.sub(r'#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{3}\b|\bwhite\b',colour,value)
        if prop in ('background','background-color'):
            value=re.sub(r'rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\)', lambda m: 'var(--surface)' if min(int(m[i]) for i in (1,2,3))>220 and float(m[4])>.3 else m[0],value)
            value=re.sub(r'rgba\(\s*255\s*,\s*255\s*,\s*255\s*,\s*\.(?:[7-9]\d*)\)', 'var(--surface)', value)
        return original_prop+':'+value
    result = re.sub(r'([\w-]+)\s*:([^;{}]+)',declaration,css)
    return '\n'.join(line.rstrip() for line in result.splitlines()).strip()

def attach(text, path):
    if not active(path,text): return text
    prefix=os.path.relpath(ROOT/'assets', (ROOT/path).parent).replace(os.sep,'/')
    text=re.sub(r' style="([^"]*)"', lambda m: ' style="'+adapt(m[1])+'"',text)
    text=re.sub(r'\n?<!-- Site presentation -->.*?<!-- /Site presentation -->', '',text,flags=re.S)
    block=f'\n<!-- Site presentation -->\n<link rel="stylesheet" href="{prefix}/presentation/shared.css">\n'
    if 'teg-blue.css' in text:
        block+=f'<link rel="stylesheet" href="{prefix}/presentation/overview.css">\n'
    inline='\n'.join(re.findall(r'<style[^>]*>(.*?)</style>',text,re.S))
    name=path.replace('/','--').replace('.html','.css')
    out=ROOT/'assets/presentation'/name
    if inline:
        out.parent.mkdir(parents=True,exist_ok=True)
        out.write_text('/* Page layout overrides; generated by scripts/presentation.py. */\n'+adapt(inline))
        block+=f'<link rel="stylesheet" href="{prefix}/presentation/{name}">\n'
    block+=f'<link rel="stylesheet" href="{prefix}/presentation/theme.css">\n<script defer src="{prefix}/presentation/layout.js"></script>\n<!-- /Site presentation -->\n'
    return re.sub(r'\s*</head>', lambda m: block+'</head>', text)

def build():
    shared=['teg-blue.css','page-responsibility.css','model-coupling.css','gradient-navigation.css','signal-depth.css','signal-map-switch.css']
    # Shared components retain their named selector namespaces. The overview
    # stylesheet is attached only to pages that already use that layout.
    (ROOT/'assets/presentation/shared.css').write_text('/* Generated shared presentation. Edit source styles or adapter. */\n'+ '\n'.join(adapt((ROOT/'assets'/p).read_text()) for p in shared[1:]))
    rows=[]
    for p in sorted(ROOT.rglob('*.html')):
        rel=p.relative_to(ROOT).as_posix(); s=p.read_text()
        is_active=active(rel,s)
        dependencies=re.findall(r'<link[^>]+href=[\"\']([^\"\']+\.css[^\"\']*)',s)
        if is_active:
            result=attach(s,rel)
            p.write_text(result)
        rows.append({'path':rel,'active':is_active,'reason':'Active navigable page' if is_active else 'Historical archive / source snapshot' if ('archive' in p.parts or 'notes' in p.parts) else 'Compatibility bookmark route','stylesheets':[x for x in dependencies if '/presentation/' not in x]})
    (ROOT/'assets/presentation/overview.css').write_text('/* Generated from teg-blue.css by presentation.py. */\n'+adapt((ROOT/'assets/teg-blue.css').read_text()))
    (ROOT/'review/page-inventory.json').write_text(json.dumps(rows,indent=2)+'\n')
    print(sum(r['active'] for r in rows),'active pages;',len(rows),'HTML files inventoried')
if __name__=='__main__':build()
